mongodb:
  image: mongo
  ports:
    - "27017:27017"

videos:
  image: videos
  ports:
    - "8000:6543"
  links:
    - mongodb:mongo
  environment:
    - DATABASE_URI=mongodb://mongo:27017/videos
  command: env/bin/pserve development.ini --reload

check_mongodb_up:
  image: mongo
  links:
    - mongodb
  command:
    bash -c "echo exit | mongo mongodb:27017"

mongodb_test:
  image: mongo
  ports:
    - "27018:27017"

check_mongodb_test_up:
  image: mongo
  links:
    - mongodb_test
  command:
    bash -c "echo exit | mongo mongodb_test:27018"

videos_test:
  image: videos
  links:
    - mongodb_test:mongo
  environment:
    - DATABASE_URI_TEST=mongodb://mongo:27018/videos
  command: pytest --cov --cov-report=term-missing
